// Auto generated by utensor-cli

#ifndef __MODELS_CIFAR10_CNN_H
#define __MODELS_CIFAR10_CNN_H
#include "uTensor/core/context.hpp"
void get_cifar10_cnn_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_CIFAR10_CNN_H